name: Pull Request CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deployDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Generate simple HTML document
        run: |
          mkdir -p example
          echo -e "<pre>$(date -u)\n$GITHUB_SHA\n$GITHUB_REF</pre>" > example/index.html

      - name: List cwd
        run: |
          cd example
          ls -la

      - name: Test action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./example"
          draft: true
          comment-on-pull-request: true
          # github-env: "development"
